apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ledger-core-api
  description: "Core bancário para registro de extratos"
  annotations:
    github.com/project-slug: emanueldeveloper82/ledger-core-api
spec:
  type: service
  lifecycle: production
  owner: group:conta-corrente
  domain: financeiro
  system: system:banking-system
  providesApis:
    - ledger-core-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ledger-core-api
  description: "Especificação OpenAPI do Ledger Core API"
spec:
  type: openapi
  lifecycle: production
  owner: group:conta-corrente
  system: system:banking-system
  definition:
    $text: ./openapi.yaml
